name: OWASP ZAP Baseline

on:
  workflow_dispatch:

jobs:
  zap:
    runs-on: ubuntu-latest
    steps:
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://localhost:4280'
          rules_file_name: zap-baseline.conf
          allow_failures: false
