name: Semgrep SAST

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  semgrep:
    name: Run Semgrep
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: returntocorp/semgrep-action@v1
        with:
          config: >- 
            p/default # OWASP Top 10 + common JS vulns
